// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5lr0HVlvzrLEqe2YOByZYvR6HrxQDaYA',
    appId: '1:789382996530:web:6492a0a10ca4079b07122b',
    messagingSenderId: '789382996530',
    projectId: 'coffee-shop-project123',
    authDomain: 'coffee-shop-project123.firebaseapp.com',
    storageBucket: 'coffee-shop-project123.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsPTOnnePXPh91nqCPjKKH1gIyZSWouDg',
    appId: '1:789382996530:android:e38f258e95dd212107122b',
    messagingSenderId: '789382996530',
    projectId: 'coffee-shop-project123',
    storageBucket: 'coffee-shop-project123.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoUMqUGiYJOsFf0ELCPmqsuaBw8M3cxhU',
    appId: '1:789382996530:ios:b8008a431c86b75a07122b',
    messagingSenderId: '789382996530',
    projectId: 'coffee-shop-project123',
    storageBucket: 'coffee-shop-project123.appspot.com',
    iosClientId: '789382996530-avvlsj4t5vg6vbtof5js49andbfel7ap.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCoffeeApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoUMqUGiYJOsFf0ELCPmqsuaBw8M3cxhU',
    appId: '1:789382996530:ios:4e7987a7f6395eff07122b',
    messagingSenderId: '789382996530',
    projectId: 'coffee-shop-project123',
    storageBucket: 'coffee-shop-project123.appspot.com',
    iosClientId: '789382996530-8e6hhj5amnar336c32i8s9q75c3e1vmb.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCoffeeApplication.RunnerTests',
  );
}
